"use client";

import { useState, useEffect } from "react";
import { Check, X, FileText, MessageSquare, Clock } from "lucide-react";

interface ApprovalItem {
  id: string;
  type: "Brief" | "Draft";
  title: string;
  submitted_at: string;
  status: "pending";
}

export default function ClientApprovalsPage() {
  const [items, setItems] = useState<ApprovalItem[]>([]);
  
  useEffect(() => {
    // Stub
    setTimeout(() => {
      setItems([
        {
          id: "1",
          type: "Brief",
          title: "Top CRM Tools Outline",
          submitted_at: new Date().toISOString(),
          status: "pending"
        },
        {
          id: "2",
          type: "Draft",
          title: "Enterprise Project Management Guide",
          submitted_at: new Date(Date.now() - 86400000).toISOString(),
          status: "pending"
        }
      ]);
    }, 400);
  }, []);

  return (
    <div className="space-y-8 animate-in fade-in duration-500 max-w-5xl">
      <div>
        <h1 className="text-3xl font-semibold tracking-tight text-slate-900 mb-2">Approvals</h1>
        <p className="text-slate-500">Review content generated by our AI and strategists.</p>
      </div>

      <div className="space-y-4">
        {items.map(item => (
          <div key={item.id} className="bg-white border border-slate-200 rounded-2xl p-6 shadow-sm flex flex-col md:flex-row md:items-center justify-between gap-4">
            <div className="flex items-start space-x-4">
              <div className={`p-3 rounded-xl ${item.type === 'Brief' ? 'bg-blue-50 text-blue-600' : 'bg-purple-50 text-purple-600'}`}>
                <FileText className="w-6 h-6" />
              </div>
              <div>
                <div className="flex items-center space-x-2">
                  <span className="text-xs font-semibold uppercase tracking-wider text-slate-400">{item.type}</span>
                  <span className="w-1 h-1 bg-slate-300 rounded-full"></span>
                  <span className="text-xs text-slate-500 flex items-center"><Clock className="w-3 h-3 mr-1" /> {new Date(item.submitted_at).toLocaleDateString()}</span>
                </div>
                <h3 className="text-lg font-semibold text-slate-900 mt-1">{item.title}</h3>
              </div>
            </div>
            
            <div className="flex space-x-3">
              <button className="flex items-center px-4 py-2 bg-white border border-slate-200 text-slate-700 rounded-lg hover:bg-slate-50 transition text-sm font-medium">
                <MessageSquare className="w-4 h-4 mr-2" />
                Review & Comment
              </button>
              <button className="flex items-center px-4 py-2 bg-emerald-600 text-white rounded-lg hover:bg-emerald-700 transition text-sm font-medium shadow-sm">
                <Check className="w-4 h-4 mr-2" />
                Approve
              </button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
